version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  
  pre_build:
    commands:
      - echo installing dependencies
      - npm install

  build:
    commands:
      - echo running tests e2e
      - npm run test:e2e
